### ISSUE TITLE
Error Using requirements.in

### ISSUE THREAD

**Issue by wesleyboar** [django-cms/django-cms-quickstart#77]
I followed `README.md` [Local setup](https://github.com/django-cms/django-cms-quickstart/blob/aa65b1d/README.rst#local-setup) —

I have a running instance, no pages.

— then [Updating requirements](https://github.com/django-cms/django-cms-quickstart/blob/aa65b1d/README.rst#updating-requirements) step 2 "Run `docker compose run --rm web pip-compile requirements.in >> requirements.txt`". I get error (even without a change to `requirements.in`, and with a page added, I get same error):

```
TypeError: RequirementCommand.make_resolver() got an unexpected keyword argument 'use_pep517'
```

<details><summary>Full Error</summary>

```sh
$ docker compose run --rm web pip-compile requirements.in >> requirements.txt
 Container django-cms-quickstart-web-run-1909ee1d92a3 Creating 
 Container django-cms-quickstart-web-run-1909ee1d92a3 Created 
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 7, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/scripts/compile.py", line 470, in cli
    results = resolver.resolve(max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/resolver.py", line 577, in resolve
    resolver = self.command.make_resolver(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RequirementCommand.make_resolver() got an unexpected keyword argument 'use_pep517'
```

</details>

<details><summary>My Change</summary>

`requirements.in`
```diff
+ 
+ # test blog feature
+ djangocms-blog

django-filer
```

</details>

**Comment by fsbraun** [comment]
Can you try:
```
docker compose run --rm web pip-compile -U requirements.in -o requirements.txt
```

Not sure it would make a difference (I'm not at all savvy with docker), but that's how I'd run the command.

**Comment by wesleyboar** [comment]
Yes. Result of `docker compose run --rm web pip-compile -U requirements.in -o requirements.txt` is the same (**`TypeError: RequirementCommand.make_resolver() got an unexpected keyword argument 'use_pep517'`**).

<details>

```sh
~/Code/_django_cms/django-cms-quickstart (main) % docker compose run --rm web pip-compile -U requirements.in -o requirements.txt
WARN[0000] No services to build                         
WARN[0000] No services to build                         
Container django-cms-quickstart-web-run-5dde413aaab3 Creating 
Container django-cms-quickstart-web-run-5dde413aaab3 Created 
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 7, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/scripts/compile.py", line 470, in cli
    results = resolver.resolve(max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/resolver.py", line 577, in resolve
    resolver = self.command.make_resolver(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RequirementCommand.make_resolver() got an unexpected keyword argument 'use_pep517'
```

</details>

**Comment by wesleyboar** [comment]
I put A.I. on the job. Upgrade to `pip-tools>=7.5.2` solved the problem, but also means the command in question will greatly change `requirements.txt`. Unless otherwise directed, I'll open:

- **both** a minimal PR, to clearly show the proposed fix
- **and** a "then I ran the command" PR, to show the full change that seems necessary

**Comment by wesleyboar** [comment]
Proposed fix: 
- either #79
- or #80

**Comment by wesleyboar** [comment]
Might be superseded or fixed or conflict with #78.

I trust maintainers, and don't mind if my PRs are declined.

**Comment by wesleyboar** [comment]
Ah, I see #78 updates `pip-tools==7.4.1` to `pip-tools==7.5.2`!
