### PR TITLE
deps: pip-tools version in requirements, fixes #77 - and update req.txt

### LINKED ISSUE #77: Error Using requirements.in
I followed `README.md` [Local setup](https://github.com/django-cms/django-cms-quickstart/blob/aa65b1d/README.rst#local-setup) —

I have a running instance, no pages.

— then [Updating requirements](https://github.com/django-cms/django-cms-quickstart/blob/aa65b1d/README.rst#updating-requirements) step 2 "Run `docker compose run --rm web pip-compile requirements.in >> requirements.txt`". I get error (even without a change to `requirements.in`, and with a page added, I get same error):

```
TypeError: RequirementCommand.make_resolver() got an unexpected keyword argument 'use_pep517'
```

<details><summary>Full Error</summary>

```sh
$ docker compose run --rm web pip-compile requirements.in >> requirements.txt
 Container django-cms-quickstart-web-run-1909ee1d92a3 Creating 
 Container django-cms-quickstart-web-run-1909ee1d92a3 Created 
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 7, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/scripts/compile.py", line 470, in cli
    results = resolver.resolve(max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/resolver.py", line 577, in resolve
    resolver = self.command.make_resolver(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RequirementCommand.make_resolver() got an unexpected keyword argument 'use_pep517'
```

</details>

<details><summary>My Change</summary>

`requirements.in`
```diff
+ 
+ # test blog feature
+ djangocms-blog

django-filer
```

</details>

### PR DESCRIPTION
**Pull request by wesleyboar**
## Overview

Fix #77 by updating pip-tools from `7.4.1` to `7.5.2`, and pinning the version[^1], **and** then updating `requirements.txt`.

## Related

- if I change and pin dependency without running the command which updates the `requirements.txt`, diff is merely #79
- #78

## Testing

1. `docker compose build web`
2. `docker compose run --rm web pip-compile -U requirements.in -o requirements.txt`[^2]
3. No error.
4. No diff.

[^1]: `7.5.0` was inadequate, error still occurred
[^2]: Differs from [README command](https://github.com/django-cms/django-cms-quickstart/blob/aa65b1d/README.rst?rgh-link-date=2026-01-16T23%3A25%3A37.000Z#updating-requirements) but suggested by contributor in #77 and considered "better" by A.I. (because it overwrites, not appends).

### CODE REVIEW

File: requirements.txt [hunk 1]
```diff
@@ -1,28 +1,28 @@
 #
-# This file is autogenerated by pip-compile with Python 3.12
+# This file is autogenerated by pip-compile with Python 3.11
```
Comment (wesleyboar) [inline requirements.txt:2]: This automated change suggests to me that the `requirements.txt` had previously been built **not** via [the `Dockerfile` currently in `main` branch which uses Python 11](https://github.com/django-cms/django-cms-quickstart/blob/742f249/Dockerfile), but by either a developer's local system or a different container.
